### ISSUE TITLE
Meeting Notes and Weekly Reports

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#15]
CS 690 Team: From this point on, please create both meeting notes and weekly reports in the wiki, and add links to those pages on the main wiki page.

@ranmocy @michellegg @yaxum62

**Comment by ranmocy** [comment]
I think we should all mark this as read, so that we can close this issue.
@michellegg @yaxum62 @Azure22

**Comment by michellegao715** [comment]
I have read this.
@ranmocy @Azure22 @yaxum62
