### ISSUE TITLE
Week 05: Wireshark Data

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#18]
Please see [Week 05: Wireshark Data](../wiki/Week-05:-Wireshark-Data) for details. Close this issue once all of you have agreed on a dataset.

@ranmocy @Azure22 @michellegg @yaxum62

**Comment by yaxum62** [comment]
http-sfgate101.pcapng
in "Wireshark 101 Essential Skills for Network Analysis (Laura Chappell)"
in http://www.netresec.com/?page=PcapFiles

**Comment by sjengle** [comment]
Link to the actual file.

**Comment by sjengle** [comment]
Describe the type of data included in this file.

**Comment by sjengle** [comment]
Upload into shared data folder on GitHub.

**Comment by yaxum62** [comment]
Data has uploaded as [sfgate.csv](http://sjengle.cs.usfca.edu/cs690-sonicwall/public/sfgate.csv)
The header of csv is
- "No.","Time","Source","Destination","Protocol","Length","Info"

It has 11678 instances
