### ISSUE TITLE
Add GPS coordinates to Wireshark Data

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#23]
Add a latitude and longitude coordinates to the source IP and destination IP address. You can use something like http://freegeoip.net/ to automate this process. Please place a new CSV with that data on GitHub.

@ranmocy @Azure22 @yaxum62 @michellegg

**Comment by xhanio** [comment]
Done.
Please check this [sfgate_with_geoip.csv](http://sjengle.cs.usfca.edu/cs690-sonicwall/public/sfgate_with_geoip.csv).
