### ISSUE TITLE
Dell Trip Scheduling

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#28]
Can everyone make Tuesday November 4, 2014 between 9:00am and 12:00pm for a trip to Dell? 

@ranmocy @Azure22 @michellegg @yaxum62

**Comment by michellegao715** [comment]
It works for me.

**Comment by ranmocy** [comment]
I think I can too.

**Comment by yaxum62** [comment]
It's OK for me

**Comment by xhanio** [comment]
I have datamining class during that timespan but I guess I can ask for leave.
Let me ask professor Cindy first.

**Comment by sjengle** [comment]
I am not 100% that this will work with my schedule yet. Lets discuss today.
