### ISSUE TITLE
Week 08 Professional Website

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#34]
Put together a professional website shell using [Bootstrap 3.0](http://getbootstrap.com/). There should be navigation links for:
- **Home** A nice landing page that gives a brief project summary and where to go for more information.
- **Visualizations** A page that will eventually display (or link to) the visualizations.
- **Data:** A page about the datasets being used for the visualizations. You should describe the original dataset, the transformations made to that dataset, and where the original and new dataset may be downloaded. For now, this will only be for the Wireshark data, but we will eventually add test SonicWALL data here too.
- **Tools:** A page about the tools being used to generate the visualizations. There should be placeholders for information on D3, P5, and Tableau.
- **Team:** A page with placeholders for photos and bios for all the student team members and project sponsors (including Xi from the directed study).

The page can differ slightly from above, as along as all this information is easily accessible. This week, only placeholders are needed. We will fill in the missing information in the data, tools, and team pages over the next few weeks. 

Please decide who will begin working on this, and assign that person to this issue. @ranmocy @yaxum62 @michellegg

**Comment by ranmocy** [comment]
Finished.
