### ISSUE TITLE
Week 08 GMS Demo

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#38]
One person should explore the [SonicWALL GMS Live Demo](http://gms.demo.sonicwall.com/). Fill in the [report on the wiki](https://github.com/sjengle/cs690-sonicwall/wiki/SonicWALL-GMS-Live-Demo) with the necessary information. 

When you have decided who will be handling this task, please assign it to that person. Close the issue when you are done.

**Comment by xhanio** [comment]
Done. [Link](https://github.com/sjengle/cs690-sonicwall/wiki/SonicWALL-GMS-Live-Demo)

**Comment by sjengle** [comment]
No screenshots :disappointed:
