### ISSUE TITLE
Week 09 Fix Weekly Reports and Meeting Notes

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#40]
Please make sure all of the previous weekly reports and meeting notes have professional formatting and grammar. (It is especially important when working in visualization to pay attention to details, such as capitalization, punctuation, and spacing.)

**Comment by ranmocy** [comment]
Fix formats.
Waiting for syntax fix.

**Comment by michellegao715** [comment]
Fix syntax and grammar.
