### ISSUE TITLE
Week 09 Team Webpage

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#43]
Please update the [Team](http://sjengle.cs.usfca.edu/cs690-sonicwall/team.html) webpage as follows:
- Make sure each person as an accurate and professional photo on this page. You can use your OneCard photos if you like, which I attached to this issue. You should also be able to find photos of me and Carrie on the web.
- Make sure each person has a professional bio. Include degrees earned or working on, current positions (if appropriate), and areas of specialization or skills. Keep each bio around 3 to 5 sentences.
- Remove the quote at the bottom of this page.

![20293816](https://cloud.githubusercontent.com/assets/1919171/4654353/5ae2dd76-54b6-11e4-9fea-5adbd31d350b.JPG)
![20304188](https://cloud.githubusercontent.com/assets/1919171/4654354/5af0bd7e-54b6-11e4-87bc-7c41c61cb033.JPG)
![20291184](https://cloud.githubusercontent.com/assets/1919171/4654355/5afb1e2c-54b6-11e4-814e-c008069bd834.JPG)
![20290945](https://cloud.githubusercontent.com/assets/1919171/4654356/5afdba74-54b6-11e4-88be-a75839a5c0b7.JPG)

**Comment by ranmocy** [comment]
@sjengle I search the web but I can't find anything useful information about Carrie Gates.
I only got a [tweet](https://twitter.com/GregPemberton/status/436217317027229696).
Can you help me to ask for some information? Like her homepage or something?
Thank you.

**Comment by sjengle** [comment]
There is some older information at https://web.cs.dal.ca/~gates/.There is a recent bio for her at http://meetings.internet2.edu/en/2014-technology-exchange/program/featured-keynotes/.

**Comment by ranmocy** [comment]
Updated.
