### ISSUE TITLE
Week 09 Tools Webpage

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#44]
Please make the following modifications to the [Tools](http://sjengle.cs.usfca.edu/cs690-sonicwall/tools.html) webpage.
- Please add in-text links for each tool. (I know the titles are linked, but everywhere "D3.js" and "p5.js" is located in the text should also link back to those webpages. It would be nice if the images linked back to the websites as well.)
- Please indicate why we are using each tool. Something like... Tableau for quick prototyping and exploring the raw data, D3 to create interactive visualizations tailored to the data, and P5 for more flexibility and better performance than D3.
- Please remove the quote at the bottom.
- It looks like the text here is copy/pasted from the websites. **DO NOT PLAGIARIZE.** Please include your own description of the tools, and/or indicate where you are quoting from the websites.
- Consider adding the Dell SonicWALL products we will be exploring.

**Comment by xhanio** [comment]
Done.
