### ISSUE TITLE
Week 09 Showcase Visualizations

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#46]
Please decide on 1 or 2 visualizations to showcase during the Skype call. 

It should be on the Wireshark data, and ideally should be interactive. I recommend you decide as a team which one to use as a starting point, and then have someone (or multiple people) dedicated to tweaking it until it is ready to show off.

**Comment by yaxum62** [comment]
The showcase is ready. It is based on Kaiming's visualization and it's still locate at (http://sjengle.cs.usfca.edu/cs690-sonicwall/kyang/week7_sfgate_again/)
