### ISSUE TITLE
Week 09 Home Webpage

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#48]
Please make the following modifications to the [Home](http://sjengle.cs.usfca.edu/cs690-sonicwall/index.html) page:
- Update the lead text. State "In this project, **we** will...".
- Think about adding some additional information below. Talk about the classes this project is for, the semester, maybe a timeline, important dates, etc. to this page.
- Please update the footer. Include information like the semester, courses involved, a link to the department, and a link to the university. 
- Please remove the quote box.

**Comment by ranmocy** [comment]
Done.
