### ISSUE TITLE
Week 10 Prepare Dataset

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#50]
One person should work on creating subsets of the Wireshark data that everyone will use. Specifically:
- Create a summary dataset from the Wireshark data that contains the top 10 source to destination hosts by amount transmitted. This will be used by the table.
  - Make sure to include the source, destination, protocol, total length (sum all entries together), and GPS coordinates.
  - Replace IP addresses by host name where possible. Use a reverse DNS lookup. There are websites for this, or use a utility like `nslookup`. There should be few enough hosts to do this manually if necessary.
- Create a filtered subset of the Wireshark data that contains the individual entries for the hosts identified above. This will hopefully load faster and result in more responsive sparkline visualizations.
  - Use the hostnames discovered for the summary dataset in this file too.
  - If possible, it would be nice to create a semi-summarized version of this filtered dataset. Meaning, sample the dataset at regular time intervals and combine entries that fall within the same window. If there are no entries within a window, the length/bytes transferred amount should be set to 0. This will speed up visualization.
- Update the repository and dataset information on the website.
- _It would also be nice to have `json` versions that can be easily loaded into D3._

This issue needs to be completed quickly, so please assign this to someone that will be able to get started right away.

**Comment by ranmocy** [comment]
Finished the summary part. But I'm not sure what's the best way to deal with the protocol.
Currently I grouped the data into by the combination of source, destination, and protocol.
Since each line of the final summary data is under the same protocol.

**Comment by ranmocy** [comment]
Finished subset data.
Summarized data by rounded_time, source, destination, protocol.
I didn't add the additional 0 data, since that will increase the data size quite a lot.

JSON files are generated also.
All files are under public dir.

**Comment by ranmocy** [comment]
Updated data page.

@michellegg @yaxum62
