### ISSUE TITLE
Week 10 Interactive P5 Area Chart

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#52]
Create a P5 sketch that will display a single interactive line or area chart. 

Try to add lots of interactivity. The ability to see specific values via hover and zoom would be great if possible.

Think about how to integrate this into the rest of the table/dashboard visualization. If a user clicks on a sparkline, it would be nice to popup a window with the P5 visualization (or to show the P5 visualization in an iframe on the same page). 

Create a sample web page with the P5 sketch.

**Comment by xhanio** [comment]
Done. [Link](http://sjengle.cs.usfca.edu/cs690-sonicwall/xihan/week10_2/)
I'm still trying to improve this.
