### ISSUE TITLE
Week 10 Responsive Table

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#54]
Create a responsive table that will automatically sort if a column is clicked. The sortable columns should include:
- Source Hostname or IP
- Source Country
- Destination Hostname or IP
- Destination Country 
- Protocol

Include non-sortable columns for sparklines that will eventually show:
- Bytes over Time (line or area)
- Total Bytes (bars)

Until those functions are working, just include placeholder images (can be a gray box).

Create a sample webpage to showcase the table.

**Comment by ranmocy** [comment]
Done.
Update link at: http://sjengle.cs.usfca.edu/cs690-sonicwall/visual.html
