### ISSUE TITLE
Week 10 Assign Issues

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#55]
We will be working to transform this:
![Scrutinizer Screenshot](https://cloud.githubusercontent.com/assets/1919171/4711371/a76981de-58b9-11e4-8ccd-a758168609bb.png)

into something that looks closer to this:
![Sparklines](http://datajournalismhandbook.org/1.0/en/figs/incoming/05-BC-graphical-table.png)

Please assign issues #50, #51, #52, #53, and #54 to individuals. Lets plan on having prototypes of each individual component ready by next week, and something integrated in time for the Dell visit. Close this issue when the assignments are made. If you have questions about specific issues, please add comments to those issues directly.

@ranmocy @yaxum62 @michellegg @Azure22

**Comment by ranmocy** [comment]
Done.
