### ISSUE TITLE
Week 11 Prepare for Site Visit

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#59]
Please prepare for the [Dell Site Visit](https://github.com/sjengle/cs690-sonicwall/wiki/Dell-Site-Visit). 

Try to pull everything together into a single visualization, prepare to demo your visualization at Dell (a mini presentation where _everyone_ speaks would be **awesome**), and clean up the website.

**Comment by ranmocy** [comment]
Assigned.
