### ISSUE TITLE
Final Delivereables

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#69]
Please create a **Deliverables** page on the website with the following items:
- **Final Report**: See #68 for details.
- **Usage Video(s)**: Create and link short video(s) that demonstrate your final visualizations. _Everyone_ should speak on the video(s) at some point.
- **CS Night Slides**: Please link to the slides you created for your CS Night Poster. 

Please make sure these are on the website by **Thursday December 11** at 1:59pm.

---

@ranmocy @yaxum62 @Azure22 @michellegg

**Comment by sjengle** [comment]
Please link to the deliverables page in a comment and close this issue when complete.

**Comment by ranmocy** [comment]
Finished: http://sjengle.cs.usfca.edu/cs690-sonicwall/deliverables.html
Though final report is still on the going, but links are there already, both web or pdf.
