### ISSUE TITLE
Repository Ownership

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#70]
After the end of the semester, I'll make a backup of this repository and then transfer ownership of this repository to one of you. Please decide who it should be and include this as a comment to this issue. 

Everyone will still have access to this repository, but its location and who has administration privileges over it will change.

---

@ranmocy   @yaxum62   @Azure22   @michellegg

**Comment by ranmocy** [comment]
@Azure22 will take it since he will continue to work on it.
Thank you.
